// <auto-generated />
namespace SCRIPTERS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialMigration));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:SCRIPTERS/Migrations/201910172139039_Initial-Migration.Designer.cs
            get { return "201910172139039_Initial-Migration"; }
=======
            get { return "201910181312341_Initial-Migration"; }
>>>>>>> 98615e966fda9f80c1a01ef10b5c679dcbc82c76:SCRIPTERS/Migrations/201910181312341_Initial-Migration.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
